# Generated by Django 5.2.5 on 2025-08-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0001_initial'),
        ('employee_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtimerequest',
            unique_together={('employee', 'attendance')},
        ),
    ]
