# Generated by Django 5.2.5 on 2025-09-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0002_alter_overtimerequest_unique_together'),
        ('employee_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests', to='attendance_module.attendance'),
        ),
        migrations.AlterField(
            model_name='workingsummary',
            name='attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_summary', to='attendance_module.attendance'),
        ),
        migrations.CreateModel(
            name='OvertimeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('overtime_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_rate', to='employee_module.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
