# Generated by Django 5.2.5 on 2025-09-04 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0003_alter_overtimerequest_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_request', to='attendance_module.attendance'),
        ),
    ]
