# Generated by Django 5.2.5 on 2025-09-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_module', '0002_alter_employeeprofile_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('type', models.CharField(choices=[('allowance', 'Allowance'), ('bonus', 'Bonus'), ('commission', 'Commission'), ('festival_allowance', 'festival allowance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_taxable', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowances', to='employee_module.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.DateField()),
                ('type', models.CharField(choices=[('late_fine', 'Late Fine / Penalty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduction', to='employee_module.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_name', models.CharField(max_length=255)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('starting_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ending_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxpayer_type', models.CharField(choices=[('SINGLE', 'single'), ('MARRIED', 'married')], max_length=20)),
            ],
            options={
                'unique_together': {('taxpayer_type', 'tax_name', 'starting_salary', 'ending_salary')},
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paying_structure', models.JSONField()),
                ('salary_pdf', models.FileField(blank=True, null=True, upload_to='media/salary/pdf_salary/')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_module.employee')),
            ],
            options={
                'unique_together': {('year', 'month', 'employee')},
            },
        ),
    ]
