# Generated by Django 5.2.5 on 2025-09-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowance',
            old_name='type',
            new_name='allowance_type',
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_annual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tax',
            name='ending_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='taxpayer_type',
            field=models.CharField(choices=[('unmarried', 'Unmarried'), ('married', 'Married')], max_length=20),
        ),
    ]
