# Generated by Django 5.2.5 on 2025-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0002_rename_type_allowance_allowance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
