# Generated by Django 5.2.5 on 2025-09-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0003_salary_deduction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='allowance_type',
            field=models.CharField(choices=[('allowance', 'Allowance'), ('bonus', 'Bonus'), ('commission', 'Commission'), ('festival_allowance', 'festival allowance'), ('meals_allowance', 'meals_allowance')], max_length=20),
        ),
    ]
