# Generated by Django 5.2.5 on 2025-09-15 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0003_employee_marital_status'),
        ('payroll_module', '0004_salary_overtime_pay_alter_allowance_allowance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary', to='employee_module.employee'),
        ),
    ]
