# Generated by Django 5.2.5 on 2025-09-18 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0004_employee_date_of_leaving'),
        ('payroll_module', '0005_alter_salary_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('changes', models.JSONField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_module.employee')),
                ('leave_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_audit', to='payroll_module.salary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
