# Generated by Django 5.2.5 on 2026-05-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingoffboardingtask',
            name='task_type',
            field=models.IntegerField(blank=True, choices=[(1, 'onboarding'), (2, 'offboarding')], null=True),
        ),
    ]
