# Generated by Django 5.2.5 on 2025-09-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0002_alter_employeeprofile_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], default='unmarried', max_length=20),
        ),
    ]
