# Generated by Django 5.2.5 on 2025-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0003_employee_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
    ]
