# Generated by Django 5.2.5 on 2026-05-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0004_employee_date_of_leaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
