# Generated by Django 5.2.5 on 2025-08-29 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0001_initial'),
        ('leave_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_paid',
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.DateField()),
                ('casual_leaves', models.PositiveIntegerField(default=0)),
                ('sick_leaves', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_balances', to='employee_module.employee')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
