# Generated by Django 5.2.5 on 2025-09-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0001_initial'),
        ('leave_module', '0002_remove_leaverequest_is_paid_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('changes', models.JSONField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_module.employee')),
                ('leave_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails', to='leave_module.leavebalance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
